version: '3.2' 

services:
  mms-api:
    image: gitlab.accessheritage.com:5050/mms2/mms-backend/mms-api:${API_TAG:-latest}
    ports:
      - "5001:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=DEV
      - ASPNETCORE_URLS=http://+:80
    volumes:
      - type: bind
        source: /home/teamcity/.gnupg
        target: /root/.gnupg

    deploy:
      placement:
        constraints: [node.role == worker]
      replicas:1
      restart_policy:
        max_attempts: 3
        condition: on-failure       
      update_config:
        parallelism: 1
        delay: 10s
    networks: 
      - mmsnet-dev

  mms-ui:
    image: gitlab.accessheritage.com:5050/mms2/mms-frontend/mms-ui:${UI_TAG:-latest}
    ports:
      - "3001:3000"
    environment:
      - API_BASE_URL=https://mms2-api-dev.accessheritage.com
      - APP_OIDC_TENANTID=1c52729b-e37a-46f3-9b7a-94d0ce8eb632
      - APP_OIDC_CLIENTID=312fdf2a-e7b0-469a-b3fc-7806c23a27d7
    depends_on:
      - mms-api

    deploy:
      placement:
        constraints: [node.role == worker]
      replicas:1
      restart_policy:
        max_attempts: 3
        condition: on-failure       
      update_config:
        parallelism: 1 
        delay: 10s 
    networks: 
      - mmsnet-dev 

networks:
  mmsnet-dev:
    driver: overlay

