version: "3.4"

services:
  api:
    image: gitlab.accessheritage.com:5050/mms2/mms-backend/mms-api:latest
    volumes:
      - ~/.aspnet/https:/https:ro
  
  ui:
    image: gitlab.accessheritage.com:5050/mms2/mms-frontend/mms-ui:latest

