version: '3.2' 

services:
  mms-identity-server:
    ports:
      - "5014:5008"
    environment:
      - ASPNETCORE_ENVIRONMENT=UAT
    networks: 
      - mmsnet-uat
        
  mms-api:
    ports:
      - "5004:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=UAT
    networks: 
      - mmsnet-uat

  mms-ui:
    ports:
      - "3004:3000"
    environment:
      - API_BASE_URL=https://mms2-api-uat.accessheritage.com
      - OIDC_AUTHORITY=https://mms2-identity-uat.accessheritage.com
    networks: 
      - mmsnet-uat 

networks:
  mmsnet-uat:
    driver: overlay

