version: "3.4"

services:
  mms-identity-server:
    image: gitlab.accessheritage.com:5050/mms2/mms-backend/mms-identity-server:${IDENTITY_TAG:-latest}
    ports:
      - "${IDENTITY_PORT}:5008"
    environment:
      - ASPNETCORE_ENVIRONMENT=${ENV_NAME}
      - ASPNETCORE_URLS=http://+:5008
    volumes:
      - type: bind
        source: /home/teamcity/.gnupg
        target: /root/.gnupg
        
  mms-api:
    image: gitlab.accessheritage.com:5050/mms2/mms-backend/mms-api:${API_TAG:-latest}
    ports:
      - "${API_PORT}:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=${ENV_NAME}
      - ASPNETCORE_URLS=http://+:80
    volumes:
      - type: bind
        source: /home/teamcity/.gnupg
        target: /root/.gnupg

  mms-ui:
    image: gitlab.accessheritage.com:5050/mms2/mms-frontend/mms-ui:${UI_TAG:-latest}
    ports:
      - "${UI_PORT}:3000"
    environment:
      - API_BASE_URL=https://mms2-api-${ENV_NAME}.accessheritage.com
      - APP_OIDC_TENANTID=${OIDC_TENANTID}
      - APP_OIDC_CLIENTID=${OIDC_CLIENTID}
    depends_on:
      - mms-api

  mms-storybook:
    image: gitlab.accessheritage.com:5050/mms2/mms-frontend/mms-storybook:${STORYBOOK_TAG:-latest}
    ports:
      - "3011:3001"
    depends_on:
      - mms-api
