version: '3.8'

services:
  mms-api:
    image: ${REGISTRY}/mms2/mms-backend/mms-api:${TAG:-latest}
  
  mms-ui:
    image: ${REGISTRY}/mms2/mms-frontend/mms-ui:${TAG:-latest}
    depends_on:
        - mms-api

