version: '3.2' 

services:
  mms-identity-server:
    ports:
      - "5014:5008"
    environment:
      - ASPNETCORE_ENVIRONMENT=UAT
    networks: 
      - mmsnet-uat
        
  mms-api:
    ports:
      - "5004:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=UAT
    networks: 
      - mmsnet-uat

  mms-ui:
    ports:
      - "3004:3000"
    environment:
      - API_BASE_URL=https://mms2-api-uat.accessheritage.com
      - APP_OIDC_TENANTID=1c52729b-e37a-46f3-9b7a-94d0ce8eb632
      - APP_OIDC_CLIENTID=b1a7daa2-1224-4a78-b3f3-bea5e24cf53d
    networks: 
      - mmsnet-uat 

networks:
  mmsnet-uat:
    driver: overlay

