---
- name: Set variables
  tags: monitoring-setup
  set_fact:
    repo_dir: "/tmp/swarm-monitoring"
    stack_name: "monitoring"

- name: Check if deployed
  tags: monitoring-setup
  shell: "docker stack ls | grep {{ stack_name }}"
  register: deployed
  ignore_errors: true

- name: Clone swarm-monitoring repository
  tags: monitoring-setup
  ansible.builtin.git:
    repo: git@gitlab.accessheritage.com:mms2/swarm-monitoring.git
    dest: "{{ repo_dir }}"
    clone: yes
    accept_hostkey: yes
    key_file: /gitlab_deploy_keys/deploy-keys
  when: deployed.stdout | length == 0

- name: Set Redis static targets
  tags: monitoring-setup
  shell: "sed -i -r '/job_name: \"redis\"$/!{p;d;};n;n;a\\          \\- {{ item }}:9121' {{ repo_dir }}/prometheus/conf/prometheus.yml"
  loop: "{{ groups['redis'] }}"
  when: deployed.stdout | length == 0

- name: Set Elasticsearch static targets
  tags: monitoring-setup
  shell: "sed -i -r '/job_name: \"elasticsearch\"$/!{p;d;};n;n;a\\          \\- {{ item }}:9114' {{ repo_dir }}/prometheus/conf/prometheus.yml"
  loop: "{{ groups['efk'] }}"
  when: deployed.stdout | length == 0

- name: Run monitoring stack
  tags: monitoring-setup
  command: "docker stack deploy -c monitoring.yml {{ stack_name }}"
  args:
    chdir: "{{ repo_dir }}"
  when: deployed.stdout | length == 0

- name: Clean
  tags: monitoring-setup
  ansible.builtin.file:
    path: "{{ repo_dir }}"
    state: absent
  when: deployed.stdout | length == 0
